### ISSUE TITLE
Kayıt, fikir beyan etme ve benzeri işlemlerin discord botu üzerine taşınması

### ISSUE THREAD

**Issue by bilinenkisi** [acikkaynak/discord-it-yardim-bot#10]
Discord üzerinde yeni gelen kişilerinin kayıtlarının alınmasını sağlamak amacıyla modal sistemi kullanılabilir. Ki aynı sistemi fikir ve hata bildirimi gibi işlemler içinde kullanılabilir bunları kolayca mongo'nun sağlamakta olduğu free cloud veritabanında depolayabileceğimizi düşünmekteyim.
Ayrıca bu konuda yardımcıda olmak isterim.

**Comment by kodbilenadam** [comment]
Şu anda bu tarz kayıt olayları onboarding ekibinin daha rahat kayıt toplayabilmesi için formlar üzerinden yapılıyor. Bu sürecin bot üzerine taşınması onboarding ekibinin üzerine ek olarak yük bindireceğini düşünüyorum. Ekip ile konuşup en kısa sürede dönüş yapacağım.

**Comment by burakygzgll** [comment]
aslında eğer dönütler goggle spreadsheet ile toplanıyorsa otomatik discorda da log düşmesi sağlanabilir. Bu sayede çok daha hızlı filtreleme yapabilirler
