### ISSUE TITLE
/projeler butonları yanıt dönemiyor.

### ISSUE THREAD

**Issue by mertnalkiran** [acikkaynak/discord-it-yardim-bot#13]
![image](https://user-images.githubusercontent.com/24571874/217554770-209bed48-4b76-4575-ac13-e8cae2534604.png)

**Comment by bilinenkisi** [comment]
[ff01a55](https://github.com/acikkaynak/discord-it-yardim-bot/commit/ff01a551f29d6d3755277492b918b0ea12b34192) ile birlikte düzeltildi.

**Comment by ramazansancar** [comment]
Bu güncelleme sonrası çözüme kavuştu. Eğer sorun tekrar oluşursa iletebilirsiniz. Teşekkürler
