### ISSUE TITLE
Yapılması İstenenler

### ISSUE THREAD

**Issue by Renanuya** [acikkaynak/discord-it-yardim-bot#35]
- [x] /sescek : Komutu kullanan kişinin yanına etiketlenen kullanıcı çekilir (ID ilede çalışacak)
- [x] /pin : Lütfen pinli mesajları kontrol edin adında bir mesaj atacak.
- [x] #yenigelensohbet kanalına her 1 saate bir atılan mesaj, sabah saatleri 30dk'da bir akşam saatleri ise 1 saatte 1. (cronjob)

**Comment by ctnkaan** [comment]
Hala yapılmadıysa yardımcı olmak isterim.

**Comment by Renanuya** [comment]
Olur yapılsa her halde yazarlardı

**Comment by bilinenkisi** [comment]
`#yenigelensohbet kanalına her 1 saate bir atılan mesaj, sabah saatleri 30dk'da bir akşam saatleri ise 1 saatte 1. (cronjob)`  için #37 PR'ın içinde basit bir çözüm entegre etmeye çalıştım bir inceleyebilirseniz sevinirim.

**Comment by bilinenkisi** [comment]
> * [x]  /sescek : Komutu kullanan kişinin yanına etiketlenen kullanıcı çekilir (ID ilede çalışacak)
> * [x]  /pin : Lütfen pinli mesajları kontrol edin adında bir mesaj atacak.
> * [ ]  #yenigelensohbet kanalına her 1 saate bir atılan mesaj, sabah saatleri 30dk'da bir akşam saatleri ise 1 saatte 1. (cronjob)

[6b7e443f3d1905e9f13b2e9083531b81e2710056](https://github.com/acikkaynak/discord-it-yardim-bot/commit/d0445af6ed54a5313b7d087c5ed0ca79c02e2747) ile birlikte ` #yenigelensohbet kanalına her 1 saate bir atılan mesaj, sabah saatleri 30dk'da bir akşam saatleri ise 1 saatte 1. (cronjob)` de tamamen entegre edildi.

**Comment by bilinenkisi** [comment]
@Renanuya id ile çalışması gereksiz olmaz mı özelliklede hatalara sebep olabileceği ile birlikte pek te bir fayda sağladığını düşünmemekteyim

**Comment by Renanuya** [comment]
> @Renanuya id ile çalışması gereksiz olmaz mı özelliklede hatalara sebep olabileceği ile birlikte pek te bir fayda sağladığını düşünmemekteyim

ID ile çalışması bir hataya sebep olmaz. IDler her kullanıcı için farklıdır ve değişmez. Fayda olarakta şöyle her üye her kanalı göremiyor. Bu yüzden kullanıcıyı etiketlerken sorun yaşayabilirsin işte bu durumda ID ile kullanım işe yarayacaktır. @bilinenkisi
