### ISSUE TITLE
[FEAT] Sohbet'te paylaşılan duyuruların spam olmasını engelleme

### ISSUE THREAD

**Issue by kodbilenadam** [acikkaynak/discord-it-yardim-bot#47]
**Özellik İsteğiniz Bir Sorunla mı İlgili? Lütfen Açıklayın.**
-
Yeni bir özellik ekleme

**İstediğiniz çözümü açıklayın**
-
ready.js içindeki yeni-gelen-sohbet kanalına düzenli olarak paylaşılan duyurular durgun saatlerde üst üste spam şeklinde gözüküyor (görsel aşağıda). Bu spam olarak gözükmesini engellemek amacı ile botun son atılan 3 mesajı kontrol edip eğer kendisinden gelen bir mesaj ise mesaj göndermemesini sağlamak.
![image](https://user-images.githubusercontent.com/7461799/218935862-2be76b1d-1753-465e-a0c0-dcbe4df0ce3b.png)

**Eğer düşündüyseniz alternatif çözümlerden bahsedin**
-

**Ekstra bilgi**
-

**Comment by lburaq** [comment]
Sorun düzeltilmediyse yardımcı olmak isterim discord dan da bana ulaşabilirsiniz: Aquila#0294

**Comment by ramazansancar** [comment]
@lburaq Bununla ilgili olarak mesaj kanalının son 50 mesajına bakarak tekrar gönderme yapacağız. Talebi PR ile iletebilirseniz dahil edelim.

**Comment by abtonc** [comment]
#50 ile çözüldü, teşekkürler
